### ISSUE TITLE
Can't install plugin on Netbeans 11.1 due to dependencies

### ISSUE THREAD

**Issue by sharpedavid** [mcdonnell-john/nb-google-java-code-formatter-plugin#3]
I built the plugin from source with `mvn package`, but when I try to install the plugin on Netbeans 11.1 I get the following messages:

> Some plugins require plugin Common Annotations to be installed.
> The plugin Common Annotations is requested in version >= 1.33 but only 1.32 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin Editor Library 2 to be installed.
> The plugin Editor Library 2 is requested in version >= 2.26.0.55.3 but only 2.24.0.55.3 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin Editor to be installed.
> The plugin Editor is requested in version >= 1.93.0.6.3.23.55 but only 1.92.0.6.3.23.55 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin Project API to be installed.
> The plugin Project API is requested in version >= 1.73 but only 1.72 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin Base Project UI API to be installed.
> The plugin Base Project UI API is requested in version >= 1.94.0.8 but only 1.93.0.8 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin UI Utilities API to be installed.
> The plugin UI Utilities API is requested in version >= 7.74 but only 7.73 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin Datasystems API to be installed.
> The plugin Datasystems API is requested in version >= 7.73 but only 7.72 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin Text API to be installed.
> The plugin Text API is requested in version >= 6.73 but only 6.72 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin Base Utilities API to be installed.
> The plugin Base Utilities API is requested in version >= 9.13 but only 9.12 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin 
> Some plugins require plugin Lookup API to be installed.
> The plugin Lookup API is requested in version >= 8.39 but only 8.38 was found.  The following plugin is affected:       NetBeans Google Code Format Plugin  Some plugins not installed to avoid potential installation problems.

![image](https://user-images.githubusercontent.com/1767127/69283194-d4bc3b00-0ba0-11ea-866e-5a59cf917fff.png)

Of course I will download Netbeans 11.2, but it seems to me that this plugin could just as easily work for Netbeans 11.0 with the right dependency definitions. Notably Apache says this on the 11.2 download page:

> The LTS release of the Apache NetBeans 11 cycle is Apache NetBeans 11.0.  The 11.1 and 11.2 releases have not been tested as heavily as the LTS  release and may therefore be less stable. Use 11.2 to use the latest  features and to provide feedback for the next LTS release, scheduled for  April 2020. Go here to download  Apache NetBeans 11.0, the current LTS release.

So I think it would be nice to have this compatible with Netbeans 11 if that is trivial to do.

I am able to install the plugin on Netbeans 11.2.

**Comment by mcdonnell-john** [comment]
Hi @sharpedavid 

Yeah it should be relatively straight forward to build against 11 as opposed to 11.2 . This is my first public plugin (last one a did a few years ago was very specific to my use case).  I'll attempt to get this issue fixed in the next release.

**Comment by mcdonnell-john** [comment]
Should be closed with PR #5
