### ISSUE TITLE
Needs documentation for how to build, install, and enable plugin

### ISSUE THREAD

**Issue by sharpedavid** [mcdonnell-john/nb-google-java-code-formatter-plugin#4]
Figuring out how to build the plugin was easy enough because I'm used to Maven, but it took me a long time to find this checkbox:

Project Properties > Formatting > Google Java Style

![image](https://user-images.githubusercontent.com/1767127/69285909-dab51a80-0ba6-11ea-8ce1-95fd14a2d0d1.png)

**Comment by mcdonnell-john** [comment]
Thanks @sharpedavid I will mark this as an enhancement and look to improve the documentation.
